# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - uses: scale-tone/az-func-as-a-graph@github-action-v1.3
      with:
        projectFolder: ${{ github.workspace }}/custom-backends/dotnet7isolated
        outputFile: my-function-graph.htm
        doNotRenderFunctions: false
        doNotRenderProxies: false

    - uses: actions/upload-artifact@v4.3.1
      with:
        path: my-function-graph.htm
        
      
